# Generated by Django 3.0.3 on 2020-03-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200301_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='parm',
            name='size',
            field=models.CharField(default='Regular', max_length=64),
        ),
        migrations.AddField(
            model_name='pasta',
            name='size',
            field=models.CharField(default='Regular', max_length=64),
        ),
        migrations.AddField(
            model_name='salads',
            name='size',
            field=models.CharField(default='Regular', max_length=64),
        ),
        migrations.DeleteModel(
            name='Platter',
        ),
    ]
