# Generated by Django 3.0.3 on 2020-03-02 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20200301_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='parm',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parmesan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pasta',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macaroni', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regular', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salads',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sicily', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subway', to=settings.AUTH_USER_MODEL),
        ),
    ]
